# Library

In [ ]:
# A library is basically a pre defined collection of already built in codes in an structured format.
# We can use the libraries to directly utilize those codes.

## Numpy Library

In [ ]:
# Advantages of Numpy Library:
# 1. Code reusability.
# 2. Time efficient.
# 3. Used to handle complex codes.

In [ ]:
# Numpy stands for numerical python.
# Numpy is a library of python which is used to work with arrays. 
# An array is a data structure which comprises of a collection of similar values.
# In python we have list to do the same task, but utilizing an array using library enhances the task by an increase of 50x as compared to a list.
# Numpy was created in 2005 by Travis Oliphant.

In [5]:
# 1 Dimensional List:
l=[1,2,3,4,5] # (In the form of a list)
print(l)
type(l)

[1, 2, 3, 4, 5]


list

In [6]:
import numpy as np

In [10]:
# 1 Dimensional Array:
a=np.array([1,2,3,4,5])
print(a)
print(type(a)) # To check the type of the array
print(a.ndim) # To check the dimension of the array

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [13]:
b=np.array((10,20,30,40))
print(b)
print(type(b))
print(a.ndim)

[10 20 30 40]
<class 'numpy.ndarray'>
1


In [15]:
# Slicing is also possible

print(b[2])

30


In [17]:
print(a[4])

5


In [18]:
print(a[-1])

5


In [21]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [29]:
print(a[1:4:2])
print(a[0:5:2])
print(a[::2])

[2 4]
[1 3 5]
[1 3 5]


In [31]:
# 0 Dimensional Array
a=np.array(30)
print(a)
print(type(a))
print(a.ndim)

30
<class 'numpy.ndarray'>
0


In [33]:
# 2 Dimensional Array

a=np.array([[3,5,7,8],[6,3,8,9],[8,6,4,2]])
print(a) # Will be displayed in the form of a matrix
print(type(a))
print(a.ndim)

[[3 5 7 8]
 [6 3 8 9]
 [8 6 4 2]]
<class 'numpy.ndarray'>
2


In [39]:
# Slicing in 2 Dimensional Array
# [[3 5 7 8]
#  [6 3 8 9]
#  [8 6 4 2]]
# Access 3 and 5

a[0,0:2:1]
# print(a[0,0:2:1])

array([3, 5])

In [43]:
a[0:2:1,3:4:1]
print(a[0:2:1,3:4:1])
print(a[0:2:1,3])

[[8]
 [9]]
[8 9]


In [45]:
a[1,0:2:1]
print(a[1,0:2:1])

[6 3]


In [48]:
print(a[0:3:2,0:2:1])

[[3 5]
 [8 6]]


In [51]:
print(a[1:3:1,1:3:1])

[[3 8]
 [6 4]]


In [53]:
print(a[0:3:2,1:4:2])

[[5 8]
 [6 2]]


In [55]:
# 3 Dimensional Array:
a=np.array([[[2,5,7],[8,4,9],[1,3,7]]])
print(a)
print(type(a))
print(a.ndim)

[[[2 5 7]
  [8 4 9]
  [1 3 7]]]
<class 'numpy.ndarray'>
3


In [57]:
a=np.array([[[2,5,7],[8,4,9]],[[1,3,7],[5,2,9]]])
print(a)
print(type(a))
print(a.ndim)

[[[2 5 7]
  [8 4 9]]

 [[1 3 7]
  [5 2 9]]]
<class 'numpy.ndarray'>
3


In [58]:
a=np.array([[[2,5,7],[8,4,9],[1,3,7]]])
print(a)
print(type(a))
print(a.ndim)

[[[2 5 7]
  [8 4 9]
  [1 3 7]]]
<class 'numpy.ndarray'>
3


In [61]:
# [[[2 5 7]
#   [8 4 9]
#   [1 3 7]]]
# [[[2,7],[1,7]]]

print(a[0,0:3:2,0:3:2])

[[2 7]
 [1 7]]


In [62]:
# Size method
a = np.array([10,20,30,40,50])
a.size

5

In [63]:
a=np.array([[3,5,7,8],[6,3,8,9],[8,6,4,2]])
a.size

12

In [64]:
# Shape Method
a=np.array([[3,5,7,8],[6,3,8,9],[8,6,4,2]])
print(a)

[[3 5 7 8]
 [6 3 8 9]
 [8 6 4 2]]


In [65]:
a.shape

(3, 4)

In [66]:
# Reshape
a=np.array([[3,5,7,8],[6,3,8,9],[8,6,4,2]])
print(a)

[[3 5 7 8]
 [6 3 8 9]
 [8 6 4 2]]


In [67]:
a.reshape(4,3)

array([[3, 5, 7],
       [8, 6, 3],
       [8, 9, 8],
       [6, 4, 2]])

In [68]:
a.reshape(2,6)

array([[3, 5, 7, 8, 6, 3],
       [8, 9, 8, 6, 4, 2]])

In [69]:
a.reshape(6,2)

array([[3, 5],
       [7, 8],
       [6, 3],
       [8, 9],
       [8, 6],
       [4, 2]])

In [70]:
a.reshape(1,12)

array([[3, 5, 7, 8, 6, 3, 8, 9, 8, 6, 4, 2]])

In [72]:
# Arange:

a=np.arange(10)
print(a)
print(type(a))
print(a.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1


In [74]:
a=np.arange(10,21)
print(a)
print(type(a))
print(a.ndim)

[10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
1


In [76]:
a=np.arange(1,10,3)
print(a)

[1 4 7]


In [77]:
# Transpose:
a=np.array([[3,5,7,8],[6,3,8,9],[8,6,4,2]])
print(a)

[[3 5 7 8]
 [6 3 8 9]
 [8 6 4 2]]


In [79]:
a.transpose()

array([[3, 6, 8],
       [5, 3, 6],
       [7, 8, 4],
       [8, 9, 2]])

In [85]:
# Mean, Max, Min
marks = np.array([100,30,50,70,66])
marks.mean()
marks.max()
marks.min()

np.int64(30)

In [84]:
# Flatten
a=np.array([[3,5,7,8],[6,3,8,9],[8,6,4,2]])
b=a.flatten()
print(b)

[3 5 7 8 6 3 8 9 8 6 4 2]


In [86]:
# Ones
a=np.ones((3,4),dtype="int8")
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [87]:
a.itemsize

1

In [88]:
# Linspace

a=np.linspace(100,400,5)
print(a)

[100. 175. 250. 325. 400.]


In [90]:
# Add 2 elements in a list normally (using list)
l=[2,4,6,8]
a=[x+2 for x in l]
print(a)

[4, 6, 8, 10]


In [92]:
# Broadcasting
# Adding in an array is simple
a=np.array([[3,5,7,8],[6,3,8,9],[8,6,4,2]])
print(a)

[[3 5 7 8]
 [6 3 8 9]
 [8 6 4 2]]


In [95]:
b=a+2
print(b)

[[ 5  7  9 10]
 [ 8  5 10 11]
 [10  8  6  4]]


In [96]:
a*5

array([[15, 25, 35, 40],
       [30, 15, 40, 45],
       [40, 30, 20, 10]])

In [97]:
# Addition of arrays:

a=np.array([1,2,3])
b=np.array([4,5,6])
a+b # Note that the size of the array should be same.

array([5, 7, 9])

In [98]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a-b

array([-3, -3, -3])

In [99]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [100]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a/b

array([0.25, 0.4 , 0.5 ])

In [103]:
# Generate Random Number

from numpy import random

a=random.randint(100)
print(a)

35


In [105]:
# Generate a random float from 0 to 1

from numpy import random
a=random.rand()
print(a)

0.11777032620585182


In [107]:
# Generate a 1-D array containing 5 random integers from 0 to 100:

from numpy import random
a=random.randint(100, size=(5))
print(a)

[16 33 24 63 90]


In [110]:
from numpy import random
n=random.rand(5)
print(n)

[0.59105986 0.98339022 0.65110348 0.28192082 0.99543749]


In [111]:
# Choice

from numpy import random
a=random.choice([5,6,7,9])
print(a)

5


In [112]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:
from numpy import random

f=random.randint(100, size=(3,5))
print(f)

[[78 94 97 99 44]
 [57 57 37 44 29]
 [ 8 87 19 73 88]]


In [113]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

from numpy import random
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)


[[7 9 9 7 9]
 [3 9 7 9 7]
 [9 9 5 7 7]]
